version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8181:80"
      - "443:443"
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./app:/var/www
      - ./nginx/logs:/var/log/nginx
    links:
      - php
  php:
    build: ./php
    volumes:
      - ./app:/var/www
    command: php-fpm

